---
version: '3.8'
services:
  postgres:
    image: docker.io/postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=mYAw3s0meB!log
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/migrations

volumes:
  postgres-data:
